Tidy mod file
kedacore/http-add-on pull request #106
Opened 2021-03-18 22:51 UTC by khaosdoctor

Removing the unstructured code object in the scaled object creation and started using go embedded templates as per what @coderanger suggested.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] A PR is opened to update the documentation on [our docs repo](https://github.com/kedacore/keda-docs)

Fixes #72

2021-03-18 23:01 UTC, khaosdoctor commented
@arschles can you please give it a review?

2021-03-18 23:02 UTC, coderanger commented
Nifty, much simpler than my old thing using vfsgen.

2021-03-19 08:25 UTC, zroubalik commented
I am curious, is there a specific reason, why don't you want to import the type from keda? You don't want to mess with dependencies? Or what is the benefit?

2021-03-19 08:51 UTC, coderanger commented
I explained it a bit on Slack but the main reason is you cannot use concrete structs with Server Side Apply and if this controller isn't using that already, it should soon. So if you have to use an Unstructured anyway, might as well make it pretty. As a secondary issue, yes dependency hell is nice to avoid.

That first issue might some day go away when controller-gen grows support for the typed apply builder syntax but that's a long way off right now (core support is going in to client-go for 1.21 as a "no really we mean it" alpha).

2021-03-19 10:34 UTC, zroubalik commented
Thanks, that make sense.

> That first issue might some day go away when controller-gen grows support for the typed apply builder syntax but that's a long way off right now (core support is going in to client-go for 1.21 as a "no really we mean it" alpha).

Is this being tracked in some kubebuilder (controller-runtime) issue? I wasn't able to find anything.

2021-03-19 18:08 UTC, coderanger commented
Not yet, not that far along :) The core support in client-go was only merged a few days ago.

2021-03-19 20:00 UTC, arschles commented
>You don't want to mess with dependencies?

@zroubalik this certainly is a nice thing, though

2021-03-19 20:03 UTC, arschles requested changes
@khaosdoctor a few requests

2021-03-19 20:03 UTC, arschles commented on pkg/k8s/scaledobject.go
> +	tpl.Execute(&scaledObjectTemplateBuffer, map[string]interface{}{
@khaosdoctor can you check the error here please?

2021-03-19 20:03 UTC, arschles commented on pkg/k8s/scaledobject.go
> +		log.Fatal(err)
@khaosdoctor instead of `log.Fatal`, can you please return the error?

2021-03-20 15:54 UTC, khaosdoctor commented
Will do :)!

2021-03-23 19:48 UTC, khaosdoctor commented
@arschles done!

2021-03-24 21:59 UTC, arschles approved these changes
looks great @khaosdoctor ✌️ 🚀

2021-03-24 21:59 UTC, merged