Expose service configuration
kedacore/http-add-on pull request #112
Opened 2021-03-23 21:12 UTC by khaosdoctor

Adding exposed configuration, for now the only configs that can be changed are the service exposed port and type because labels are defined by the add-on.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] A PR is opened to update the documentation on [our docs repo](https://github.com/kedacore/keda-docs)

Fixes #107

2021-04-06 18:15 UTC, khaosdoctor commented
@arschles @tomkerkhove can you PTAL? Just finished

2021-04-12 19:52 UTC, arschles requested changes
LGTM @khaosdoctor. Can you add documentation to [the reference](https://github.com/kedacore/http-add-on/blob/main/docs/ref/http_scaled_object.md)?

2021-04-13 14:04 UTC, khaosdoctor commented
Will do!

2021-04-14 17:27 UTC, arschles requested changes
@khaosdoctor one more thing - can you add a test for this too?

2021-04-27 18:30 UTC, khaosdoctor commented
Commited the requested changes, but haven't done the test yet because I'm having some issues running Go in my PC, also I think we'll need to run `mage manifests` again to rebuild the RBAC config and CRD struct

2021-04-27 19:16 UTC, arschles requested changes
@khaosdoctor will this mean we need to make changes to https://github.com/kedacore/charts/pull/137 as well?

2021-04-27 19:16 UTC, arschles commented on docs/ref/http_scaled_object.md
> +## Replicas
@khaosdoctor can you add this to the example yaml above?

2021-04-29 13:03 UTC, khaosdoctor commented
> @khaosdoctor will this mean we need to make changes to [kedacore/charts#137](https://github.com/kedacore/charts/pull/137) as well?

Most likely yes, since the CRD will change (we may need to think in an automated way to do this)

2021-05-06 00:05 UTC, arschles commented
@khaosdoctor in that case, do you think we need to bump the version of the CRD?

2021-05-06 19:48 UTC, khaosdoctor commented
> @khaosdoctor in that case, do you think we need to bump the version of the CRD?

This might be a good idea, since this is a breaking change I propose a major version increase

2021-05-06 22:45 UTC, arschles commented
>This might be a good idea, since this is a breaking change I propose a major version increase

would it, though? if you're just adding a new field to the spec, it won't break old `HTTPScaledObject`s. we could bump from `v1alpha1` -> `v1alpha2`

2021-05-14 16:08 UTC, khaosdoctor commented
> >This might be a good idea, since this is a breaking change I propose a major version increase
> 
> 
> 
> would it, though? if you're just adding a new field to the spec, it won't break old `HTTPScaledObject`s. we could bump from `v1alpha1` -> `v1alpha2`

Agreed, we can keep the version and change the release :)

2021-06-15 21:23 UTC, arschles commented
@khaosdoctor this looks great. I want to get the 0.1.0 release out before we merge this though. stand by :)

2021-07-28 20:01 UTC, khaosdoctor commented
Closing it as it's gonna be superseeded by #206

2021-07-28 20:01 UTC, closed without merging