fix documentation for creating an HTTPScaledObject
kedacore/http-add-on pull request #351
Opened 2021-12-16 08:37 UTC by iompo

_Provide a description of what has been changed_

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)

Fixes #

2022-01-05 19:41 UTC, arschles requested changes

2022-01-05 19:41 UTC, arschles commented on docs/walkthrough.md
> +You interact with the operator via a CRD called `HTTPScaledObject`. This CRD object points the request for an `Host` to a `Service`. To get an example app up and running, read the notes below and the
I added a suggestion below to clarify how the CRD works with the interceptor

```suggestion
You interact with the operator via a CRD called `HTTPScaledObject`. This CRD object instructs interceptors to forward requests for a given host to your app's backing `Service`. To get an example app up and running, read the notes below and then run the subsequent command from the root of this repository.
```

2022-02-08 19:02 UTC, arschles commented
@iompo are you still interested in getting this PR merged?

2022-02-09 14:45 UTC, iompo commented
Hi @arschles sorry I totally forgot to apply the changes

2022-02-09 17:26 UTC, arschles approved these changes

2022-02-15 19:07 UTC, merged

2022-02-15 19:07 UTC, arschles commented
Thanks for this @iompo!