Change file name to better reflect contents
kedacore/http-add-on pull request #45
Opened 2021-02-04 20:23 UTC by khaosdoctor

_Image names are wrong after #40 on charts_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #44

2021-02-04 20:23 UTC, khaosdoctor commented
Add @arschles for review

2021-02-04 20:30 UTC, arschles commented
Looks good @khaosdoctor . gonna wait until we get #40 merged to do this

2021-02-08 21:40 UTC, arschles requested changes
@khaosdoctor the images names will need to use the `:latest` tag. I know you're out today, so I'll open a new PR with that change in it, close this one, and credit you in the new one - so we can do the release.

2021-02-09 07:20 UTC, tomkerkhove commented on charts/keda-http-operator/values.yaml
> +externalScalerImage: ghcr.io/kedacore/http-add-on-scaler
It's a nit, but it's best to use some structure and be more consistent:
```suggestion
images:
  operator: ghcr.io/kedacore/http-add-on-operator
  interceptor: ghcr.io/kedacore/http-add-on-interceptor
  externalScaler: ghcr.io/kedacore/http-add-on-scaler
```

You'll have to update all references though.

2021-02-09 17:02 UTC, closed without merging