Add docs for integration of keda http addon with istio
kedacore/http-add-on pull request #953
Opened 2024-03-23 09:01 UTC by nikhilchintawar

Added documentation for using keda http addon with istio in new file integrations.md. 

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [ ] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)

2024-03-23 13:43 UTC, tomkerkhove requested changes
LGTM, but a massive nit - To align with our marketing guidelines, can you rename "Keda" to "KEDA" please?

2024-03-24 06:59 UTC, nikhilchintawar commented
> LGTM, but a massive nit - To align with our marketing guidelines, can you rename "Keda" to "KEDA" please?

Done

2024-03-24 13:15 UTC, tomkerkhove approved these changes

2024-03-24 18:54 UTC, JorTurFer approved these changes
AWESOME! 
Thanks a lot for the contribution! ❤️❤️❤️❤️

2024-03-24 19:17 UTC, merged